### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by adamltyson**

### CODE REVIEW

**Review by niksirbi — APPROVED** [review]
Why drop py3.9? Is it reaching EOL already?

**Comment by niksirbi** [comment]
Also, perhaps related, the python version shield displayed in the README seems to point to `cellfinder` on PyPI, instead of `fancylog`. So maybe that shield will no longer display the correct info after the bump?

**Comment by niksirbi** [comment]
> Why drop py3.9? Is it reaching EOL already?

NVM, just say [the SPEC](https://scientific-python.org/specs/spec-0000/)

**Comment by adamltyson** [comment]
> Also, perhaps related, the python version shield displayed in the README seems to point to cellfinder on PyPI, instead of fancylog. So maybe that shield will no longer display the correct info after the bump?

Thanks, just fixed it (must have copied and pasted years ago!).

**Pull request merged**
